import os
import streamlit as st

FINNHUB_API_KEY = os.getenv("FINNHUB_API_KEY", "")
MARKETAUX_API_KEY = os.getenv("MARKETAUX_API_KEY", "")

if "FINNHUB_API_KEY" in st.secrets:
    FINNHUB_API_KEY = st.secrets["FINNHUB_API_KEY"]

if "MARKETAUX_API_KEY" in st.secrets:
    MARKETAUX_API_KEY = st.secrets["MARKETAUX_API_KEY"]
